kyverno/playground

backend/main.go
=> fix: status code

backend/main.go
This PR fixes invalid resource parsing.
=> fix: invalid resource parsing

.github/workflows/golangci-lint.yaml, .gitignore, Makefile, backend/main.go
This PR embeds frontend in backend binary.
=> feat: embed frontend in backend binary

backend/go.mod, backend/main.go, backend/main_test.go, frontend/src/components/ValidationButton.vue
This PR uses structured context.
=> feat: use structured context

backend/main.go
This PR initialises engine context.
=> fix: setup engine context

frontend/src/components/ErrorBar.vue, frontend/src/components/PolicyEditor.vue, frontend/src/components/ResourceEditor.vue, frontend/src/components/StatusChip.vue, frontend/src/components/ValidationButton.vue, frontend/src/components/ValidationDialog.vue, frontend/src/mapper.ts, frontend/src/types.ts
* show skipped result for policy/resource mismatch
* show error if YAML errors in editors are detected
=> feat: improve validation

.dockerignore, Dockerfile, Makefile, backend/main.go, frontend/.dockerignore
Provide Dockerfile and basic make command
=> feat: provide dockerfile

backend/main.go
This PR adds mutations support in the backend.
=> feat: add mutations support

.github/dependabot.yaml
This PR fixes dependabot config.
=> fix: dependabot config

backend/main.go
This PR adds gin mode support.
=> feat: add gin mode support

.github/workflows/img.yaml, Makefile
This PR publishes docker image.
=> feat: publish image

.github/workflows/img.yaml
This PR fixes ko publish workflow (removes cancellation)
=> fix: ko publish workflow

backend/main.go
This PR adds image verification support.
Can be tried with:
```yaml
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
name: check-image
spec:
validationFailureAction: Enforce
background: false
webhookTimeoutSeconds: 30
failurePolicy: Fail
rules:
- name: check-image
match:
any:
- resources:
kinds:
- Pod
verifyImages:
- imageReferences:
- "ghcr.io/kyverno/test-verify-image*"
attestors:
- count: 1
entries:
- keys:
publicKeys: |-
-----BEGIN PUBLIC KEY-----
MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8nXRh950IZbRj8Ra/N9sbqOPZrfM
5/KAQN0/KjHcorm/J5yctVd7iEcnessRQjU917hmKO6JWVGHpDguIyakZA==
-----END PUBLIC KEY-----
```
```yaml
apiVersion: v1
kind: Pod
metadata:
labels:
run: nginx
name: nginx
namespace: default
spec:
containers:
- image: ghcr.io/kyverno/test-verify-image:signed
name: nginx …
```
=> feat: add image verification support

frontend/package-lock.json, frontend/package.json, frontend/src/components/EditorToolbar.vue, frontend/src/components/MutationTable.vue, frontend/src/components/ValidationDialog.vue, frontend/src/pages/MutationDetails.vue, frontend/src/types.ts
=> feat: visualize imageVerification results

backend/main.go, backend/main_test.go, frontend/src/components/ValidationButton.vue
This PR fixes request fields names (`policy` -> `policies`)
@fjogeleit it will require some frontend changes too.
=> fix: request fields names

backend/go.mod, backend/go.sum, backend/main.go
=> fix: policy loading

.github/workflows/golangci-lint.yaml, Makefile, backend/data/data.go, backend/main.go
This PR fixes linter failures 🤞
=> fix: linter failures

Makefile
This PR adds missing help comments in makefile.
=> fix: add missing help comments in makefile

frontend/src/components/AppBar.vue, frontend/src/pages/Home.vue, frontend/src/pages/MutationDetails.vue
=> feat: add kyverno documentation link

backend/main.go, frontend/public/schemas/context.json, frontend/src/assets/templates.ts
* proposal to mock/support variables from external sources like ConfigMaps
* Split Context field in Context and Variables
* Load Variables into JSONContext
=> feat: support variables

Makefile, scripts/config/kind.yaml
This PR adds makefile targets to create/delete kind cluster.
=> chore: add makefile targets to create/delete kind cluster

Makefile
This PR adds makefile targets to deploy helm locally
=> chore: add makefile targets to deploy helm locally

backend/.goreleaser.yaml
This PR adds ko config to go releaser.
=> release: add ko config

.github/workflows/helm.yaml
This PR adds helm release workflow.
=> chore: add helm release workflow

.github/workflows/release.yaml, backend/.goreleaser.yaml
=> chore: fix ko release

backend/main.go
This PR allows registry access from context.
=> fix: allow registry access from context

.github/workflows/release.yaml
=> fix: ko release

.github/workflows/helm.yaml
=> fix: helm release

frontend/public/tutorials/context/check-serviceaccount.yaml, frontend/public/tutorials/context/exclude-namespaces-dynamically.yaml, frontend/public/tutorials/context/require-netpol.yaml, frontend/public/tutorials/context/restrict-ingress-host.yaml, frontend/public/tutorials/context/restrict-pod-count-per-node.yaml, frontend/public/tutorials/policies/allowed-pod-priorities/context.yaml, frontend/public/tutorials/policies/generation/context.yaml, frontend/public/tutorials/policies/mutation/context.yaml, frontend/public/tutorials/policies/validate/context.yaml, frontend/public/tutorials/policies/verify-images/context.yaml, frontend/src/assets/templates.ts
This PR removes unnecessary quotes from context.
Fixes #125
=> fix: remove unnecessary quotes from context

frontend/src/components/AppBar.vue
This PR fixes playground title.
Fixes #112
=> fix: playground title

README.md
This PR adds install section in readme.
Fixes https://github.com/kyverno/playground/issues/66
=> docs: add install section in readme

frontend/src/components/AppBar.vue, frontend/src/components/ContextEditor.vue, frontend/src/components/MsgTooltip.vue, frontend/src/components/MutationTable.vue, frontend/src/components/PolicyEditor.vue, frontend/src/components/ResourceEditor.vue, frontend/src/components/ValidationTable.vue, frontend/src/pages/Home.vue
#123 
#122 
#113 
#120 
#114 
#126
=> fix: UI Fixes

.github/workflows/ci.yaml, Makefile
This PR adds a workflow to verify codegen.
=> chore: verify codegen workflow

backend/go.mod, backend/go.sum, backend/main.go, frontend/public/schemas/context.json, frontend/public/tutorials/context/check-serviceaccount.yaml, frontend/public/tutorials/context/exclude-namespaces-dynamically.yaml, frontend/public/tutorials/context/require-netpol.yaml, frontend/public/tutorials/context/restrict-ingress-host.yaml, frontend/public/tutorials/context/restrict-pod-count-per-node.yaml, frontend/public/tutorials/policies/allowed-pod-priorities/context.yaml, frontend/public/tutorials/policies/generation/context.yaml, frontend/public/tutorials/policies/mutation/context.yaml, frontend/public/tutorials/policies/validate/context.yaml, frontend/public/tutorials/policies/verify-images/context.yaml, frontend/src/assets/templates.ts
This PR adds kubernetes version in context.
Fixes https://github.com/kyverno/playground/issues/143
=> feat: add kubernetes version in context

backend/main.go
This PR improves resource loading.
=> fix: improve resource loading

frontend/src/components/EditorToolbar.vue, frontend/src/config.ts, frontend/src/pages/Home.vue
=> feat: panel info via tooltip

backend/main.go, charts/kyverno-playground/README.md, charts/kyverno-playground/templates/deployment.yaml, charts/kyverno-playground/values.yaml, frontend/src/App.vue, frontend/src/components/ContextPanel.vue, frontend/src/components/ShareButton.vue, frontend/src/components/Sponsor.vue, frontend/src/pages/Home.vue
=> feat: optional sponsor text

frontend/src/composables/onboarding.ts, frontend/src/config.ts
=> fix: small typos

frontend/public/templates/clusterrole.yaml, frontend/public/templates/clusterrolebinding.yaml, frontend/public/templates/cronjob.yaml, frontend/public/templates/daemonset.yaml, frontend/public/templates/job.yaml, frontend/public/templates/namespace.yaml, frontend/public/templates/networkpolicy.yaml, frontend/public/templates/persistedvolume.yaml, frontend/public/templates/persistedvolumeclaim.yaml, frontend/public/templates/poddisruptionbudget.yaml, frontend/public/templates/priorityclass.yaml, frontend/public/templates/replicaset.yaml, frontend/public/templates/resourcequota.yaml, frontend/public/templates/role.yaml, frontend/public/templates/rolebinding.yaml, frontend/public/templates/serviceaccount.yaml, frontend/public/templates/statefulset.yaml, frontend/src/components/TemplateButton.vue
=> feat: add more templates

backend/main.go
This PR fixes the empty document case.
=> fix: empty document

charts/kyverno-playground/Chart.yaml, charts/kyverno-playground/README.md
=> release 0.1.0

backend/main.go
Removes the route / api logging
```
[GIN] 2023/05/16 - 18:44:05 | 200 |      69.131µs |      10.244.5.1 | GET      "/"
[GIN] 2023/05/16 - 18:44:05 | 200 |      82.867µs |      10.244.5.1 | GET      "/"
[GIN] 2023/05/16 - 18:44:15 | 200 |      72.758µs |      10.244.5.1 | GET      "/"
[GIN] 2023/05/16 - 18:44:15 | 200 |      21.961µs |      10.244.5.1 | GET      "/"
[GIN] 2023/05/16 - 18:44:25 | 200 |      55.215µs |      10.244.5.1 | GET      "/"
[GIN] 2023/05/16 - 18:44:25 | 200 |      14.449µs |      10.244.5.1 | GET      "/"
[GIN] 2023/05/16 - 18:44:35 | 200 |      85.641µs |      10.244.5.1 | GET      "/"
[GIN] 2023/05/16 - 18:44:35 | 200 |      60.083µs |      10.244.5.1 | GET      "/"
[GIN] 2023/05/16 - 18:44:45 | 200 |      73.518µs |      10.244.5.1 | GET      "/"
[GIN] 2023/05/16 …
```
=> fix: remove logging

charts/kyverno-playground/Chart.yaml
This PR fixes chart app version.
=> fix: chart app version

docs/RELEASE.md
=> fix: release docs

backend/go.mod, backend/go.sum
=> chore: bump a few deps

.vscode/launch.json, Makefile, backend/main.go
This PR allows enabling gin logger.
Fixes #171
=> feat: optional loger

.github/workflows/pr.yaml
This PR adds a github workflow to install helm chart
=> chore: add github workflow to install helm chart

.github/workflows/pr.yaml, .github/workflows/push-main.yaml, .github/workflows/release-chart.yaml, .github/workflows/release-goreleaser.yaml
This PR checks GH actions are pinned.
=> chore: check pinned actions

.github/workflows/pr.yaml, .github/workflows/push-main.yaml, .github/workflows/release-goreleaser.yaml
This PR fixes sign image step name.
=> fix: sign image step name

.github/workflows/push-main.yaml
=> fix: ko publish

frontend/src/components/AppVersion.vue, frontend/src/pages/Home.vue, frontend/vite.config.ts
Showing AppVersion if provided. Can set at build time by setting `APP_VERSION` node environment variable:
```
APP_VERSION="0.1.0" npm run build
```
=> feat: show app version

Makefile
This PR adds app version in makefile.
=> fix: add app version in makefile

frontend/index.html
This PR sets a black background.
=> fix: set black background

.gitignore, Makefile, backend/data/data.go, backend/main.go, backend/pkg/server/server.go
This PR creates a server package.
=> refactor: create server package

backend/main.go, backend/pkg/server/server.go
This PR adds graceful backend shutdown
=> feat: graceful backend shutdown

frontend/src/components/AppBar/ExportButton.vue, frontend/src/components/AppBar/LoadButton.vue, frontend/src/components/AppBar/SaveButton.vue, frontend/src/composables/input.ts, frontend/src/composables/state.ts, frontend/src/functions/export.ts, frontend/src/functions/share.ts, frontend/src/store/index.ts
* adds config to the share content
* sets the config to the defaults
=> feat: share config

backend/main.go, backend/pkg/config/config.go
This PR fixes `config.New` name.
=> fix: config.New name

.vscode/launch.json, Makefile
This PR adds kubeconfig in vscode debug.
=> chore: add kubeconfig in vscode debug

backend/pkg/api/handler.go, backend/pkg/api/model.go, backend/pkg/server/api/config/routes.go, backend/pkg/server/api/routes.go, backend/pkg/server/server.go
=> refactor: api config

frontend/src/components/AppBar/ExportButton.vue, frontend/src/components/AppBar/ImportButton.vue, frontend/src/components/AppBar/SaveButton.vue
=> fix: import/export button nameing and icons

Makefile
* Build frontend within docker and copy it to the backend
=> feat: build backend assets with docker

README.md
This PR adds public website to README.
=> chore: add public website to README

README.md, docs/BUILD.md, docs/README.md
This PR adds build docs.
Fixes https://github.com/kyverno/playground/issues/64
=> docs: add build docs

frontend/src/composables/onboarding.ts
Closes #115 
Proposes new English text for the Onboarding wizard.
=> update onboarding text blobs

frontend/src/composables/onboarding.ts, frontend/src/config.ts
Closes #124 
Tweaks tooltip text
=> Tweak tooltips

README.md, docs/CLUSTER.md, docs/README.md
This PR adds cluster connected docs.
=> docs: add cluster connected docs

charts/kyverno-playground/Chart.yaml, charts/kyverno-playground/README.md
=> chore: release v0.2.0

.github/workflows/release-goreleaser.yaml
This PR fixes incorrect version.
=> fix: incorrect version

backend/.goreleaser.yaml
This PR adds `-trimpath` flag.
=> chore: trim path flag

docs/RELEASE.md
=> chore: fix release docs

backend/pkg/api/handler.go, backend/pkg/cluster/cluster.go, backend/pkg/engine/exception.go, backend/pkg/engine/processor.go, backend/pkg/engine/processor_test.go
This PR adds exceptions support.
=> feat: add exceptions support

.github/workflows/release-goreleaser.yaml
testing https://github.com/goreleaser/goreleaser/pull/4038
=> chore: test goreleaser fix

backend/.goreleaser.yaml
Fixes https://github.com/kyverno/playground/issues/251
=> chore: add latest tag to stable releases

.github/workflows/release-goreleaser.yaml, backend/.goreleaser.yaml
Updates goreleaser to a version that includes fix PRs:
- https://github.com/goreleaser/goreleaser/pull/4043
- https://github.com/goreleaser/goreleaser/pull/4038
=> chore: fix latest tag release

frontend/src/composables/onboarding.ts
=> Update onboarding wizard text

backend/pkg/auth/auth.go, backend/pkg/auth/helpers.go, backend/pkg/auth/self.go, backend/pkg/auth/subject.go, backend/pkg/cluster/cluster.go
We should move this in kyverno directly.
=> feat: add auth check when listing kinds

frontend/src/components/Advanced/AdvancedConfigDialog.vue, frontend/src/components/Advanced/KyvernoConfig.vue, frontend/src/components/AdvancedDrawer.vue, frontend/src/components/ClusterButton.vue, frontend/src/components/Panel/ClusterCRDButton.vue, frontend/src/components/Panel/ClusterExceptionButton.vue, frontend/src/components/Panel/ClusterPolicyButton.vue, frontend/src/components/Panel/ClusterResourceButton.vue, frontend/src/composables/onboarding.ts
=> feat: add cluster and upload btns for config panels

frontend/src/components/Panel/PolicyEditor.vue
* delay suggestion 1,5 sec
* reset the timer when typing
#348
=> fix: delay suggestions

backend/pkg/cluster/cluster.go, backend/pkg/cluster/fake.go, backend/pkg/server/api/engine/handler.go, backend/pkg/server/api/engine/request.go
Fixes https://github.com/kyverno/playground/issues/361
=> feat: add support for cluster openapi client

frontend/src/components/Advanced/AdvancedConfigDialog.vue, frontend/src/components/Advanced/KyvernoConfig.vue, frontend/src/components/Advanced/TemplateButton.vue, frontend/src/components/AdvancedDrawer.vue, frontend/src/composables/templates.ts
=> feat: custom config templates

backend/pkg/server/api/engine/request.go
=> fix: add kyverno schemas to resource loader

backend/pkg/cluster/cluster.go, backend/pkg/cluster/fake.go, backend/pkg/cluster/policy_exception.go, backend/pkg/engine/model.go, backend/pkg/server/api/engine/handler.go, frontend/public/schemas/context.json, frontend/public/tutorials/context/check-serviceaccount.yaml, frontend/public/tutorials/context/exclude-namespaces-dynamically.yaml, frontend/public/tutorials/context/require-netpol.yaml, frontend/public/tutorials/context/restrict-ingress-host.yaml, frontend/public/tutorials/context/restrict-pod-count-per-node.yaml, frontend/public/tutorials/policies/allowed-pod-priorities/context.yaml, frontend/public/tutorials/policies/generation/context.yaml, frontend/public/tutorials/policies/mutation/context.yaml, frontend/public/tutorials/policies/validate/context.yaml, frontend/public/tutorials/policies/verify-images/context.yaml, frontend/src/assets/templates.ts, release-notes/v0.4.0.md
Fixes https://github.com/kyverno/playground/issues/355
=> feat: add exceptions related flags support

backend/pkg/engine/model.go, backend/pkg/engine/processor.go, frontend/public/schemas/context.json, frontend/public/tutorials/context/check-serviceaccount.yaml, frontend/public/tutorials/context/exclude-namespaces-dynamically.yaml, frontend/public/tutorials/context/require-netpol.yaml, frontend/public/tutorials/context/restrict-ingress-host.yaml, frontend/public/tutorials/context/restrict-pod-count-per-node.yaml, frontend/public/tutorials/policies/allowed-pod-priorities/context.yaml, frontend/public/tutorials/policies/generation/context.yaml, frontend/public/tutorials/policies/mutation/context.yaml, frontend/public/tutorials/policies/validate/context.yaml, frontend/public/tutorials/policies/verify-images/context.yaml, frontend/src/assets/templates.ts
Fixes https://github.com/kyverno/playground/issues/356
TODO: this is not thread safe :(
=> feat: add cosign related flags support

backend/go.mod, backend/go.sum, backend/main.go
For reference https://github.com/kubernetes-sigs/controller-runtime/pull/2367
=> fix: logger panic using vincepri ctrl-runtime fork

frontend/src/components/HelpButton.vue
Update Helper Text,
maybe @chipzoller can have a general look on it if we should add some new features / changes.
=> chore: update helper text

charts/kyverno-playground/Chart.yaml, charts/kyverno-playground/README.md, release-notes/v0.3.3.md
Missing release notes for https://github.com/kyverno/playground/pull/412
cc @fjogeleit
=> release v0.3.3

backend/pkg/cluster/contextloader.go
This PR uses registry client in context loader.
=> fix: use registry client in context loader

backend/pkg/engine/mocks/contextloader.go, backend/pkg/engine/mocks/contextloaderfactory.go, backend/pkg/engine/models/imagedata.go, backend/pkg/engine/models/parameters.go, backend/pkg/engine/processor.go
@fjogeleit this is for https://github.com/kyverno/playground/issues/128 but we will need some frontend too.
=> feat: add fake image data support

backend/go.mod, backend/go.sum, backend/pkg/engine/mocks/toggles.go, backend/pkg/engine/processor.go
=> feat: add support for ProtectManagedResources and ForceFailurePolicyIgnore toggles

charts/kyverno-playground/Chart.yaml, charts/kyverno-playground/README.md, release-notes/v0.3.4.md
=> release v0.3.4

Makefile, scripts/config/no-ingress/kyverno-playground.yaml
This PR fixes helm install in ci.
=> fix: helm install in ci

.github/workflows/release-goreleaser.yaml, backend/.goreleaser.yaml
This PR enables release images for all platforms.
=> fix: release images for all platforms

backend/go.mod, backend/go.sum, backend/pkg/resource/loader/loader.go, backend/pkg/resource/loader/loader_test.go
This PR bumps kubectl validate (and switches to upstream).
=> fix: bump kubectl validate

backend/pkg/engine/models/convert.go, backend/pkg/engine/models/response.go
This PR fixes the policy in the response.
NOTE: it won't work with VAPs
=> fix: policy in the response

backend/pkg/server/api/engine/handler.go
=> fix: policy loader

frontend/public/tutorials/tutorials.json, frontend/public/tutorials/validating-admission-policies/check-deployment-replicas/check-deployment-replicas.yaml, frontend/public/tutorials/validating-admission-policies/check-deployment-replicas/resource.yaml, frontend/public/tutorials/validating-admission-policies/disallow-host-namespaces/disallow-host-namespaces.yaml, frontend/public/tutorials/validating-admission-policies/disallow-host-namespaces/resource.yaml, frontend/public/tutorials/validating-admission-policies/disallow-host-path/disallow-host-path.yaml, frontend/public/tutorials/validating-admission-policies/disallow-host-path/resource.yaml
This PR adds tutorial for Validating Admission Policies.
Closes #502
=> chore: add validating admission policies tutorial

release-notes/main.md
=> chore: update release notes

backend/go.mod, backend/go.sum, backend/pkg/engine/mocks/contextloader.go
This PR uses use kyverno v1.11.0-beta.2
=> chore: use kyverno v1.11.0-beta.2

.github/cherry-pick-bot.yml
This PR adds cherry pick bot config
=> chore: add cherry pick bot

backend/pkg/server/api/cluster/routes.go
=> fix: remove todo

Makefile
This PR uses beta.2 in makefile
=> fix: use beta.2 in makefile

backend/go.mod, backend/go.sum
This PR bumps kubectl-validate.
=> chore: bump kubectl-validate

frontend/public/tutorials/context/restrict-ingress-host.yaml
=> (fix): add missing variable for unique-ingress-host tutorial

frontend/src/components/Panel/UploadButton.vue
Updated the upload icon in the UploadButton.vue component from a simple up-arrow to a more descriptive file-with-arrow icon, improving visual clarity for users.
- Updated icon in `frontend/src/components/Panel/UploadButton.vue`
- Changed from "mdi-upload" to "mdi-file-upload" for better visual representation
- The new icon provides clearer indication of the upload function
This change makes the upload function more immediately recognizable and follows standard file operation UI patterns, improving visual clarity for users.
- More intuitive user experience
- Better visual communication
- No changes to functionality
Fixes #839
=> fix: Update upload icon to file-with-arrow design - Fixes #839
